backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# publish_mode: editorial_workflow

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "existing" # Used in routes, e.g., /admin/collections/existing
    label: "Existing Content" # Used in the UI
    folder: "content/existing/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template: title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Page #", name: "weight", widget: number}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "to-create" # Used in routes, e.g., /admin/collections/to-create
    label: "Content to Create" # Used in the UI
    folder: "content/to-create/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template: title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Page #", name: "weight", widget: number}
      - {label: "Body", name: "body", widget: "markdown"}


